#!/bin/bash
while true; do
	username=$(whiptail --cancel-button "Exit" --inputbox "Enter username:" 8 39 "" --title "Change Password" 3>&1 1>&2 2>&3)
	if [ $? != 0 ]; then continue 2; fi
	if [ -z "$username" ]; then whiptail --msgbox "Please enter a username." 8 40 --title "Change Password"; continue; fi 
	break
done
while true; do
      pass1=$(whiptail --cancel-button "Exit" --passwordbox "Enter your password" 8 78 --title "Change Password" 3>&1 1>&2 2>&3)
      if [ $? != 0 ]; then continue 2; fi
      if [ -z "$pass1" ]; then
        whiptail --title "Error" --msgbox "You entered empty password." 8 78
        continue
      fi
#########################################################
#confirmation of password
      pass2=$(whiptail --cancel-button "Exit" --passwordbox "Confirm your password" 8 78 --title "Change Password" 3>&1 1>&2 2>&3)
      if [ $? != 0 ]; then continue 2; fi
      
      if [ "$pass1" == "$pass2" ]; then
        echo "$pass1" | passwd ${username} --stdin
        whiptail --msgbox "$username password changed successfully" 8 40 --title "Change password"
        break
      else
        whiptail --title "Error" --msgbox "You entered unmatch passwords." 8 78
        continue
      fi
done

