#!/bin/bash

while true; do
# Use whiptail to prompt for the username
USER=$(whiptail --cancel-button "Exit" --inputbox "Enter the username:" 8 40 --title "Disable User Account" 3>&1 1>&2 2>&3)
if [ $? != 0 ]; then continue 2; fi
###############################################################
# Check if the user entered a username
if [ -n "$USER" ]; then
# Use the usermod command to disable the user's account by setting the password to an invalid value
	usermod -L -e 1 "$USER"
################################################################    
# Use the passwd command to print the account status as "Locked" (locked)
	STATUS=$(passwd -S "$USER" | awk '{print $2}')

# Use whiptail to display a message confirming the user's account was disabled and display account status
	whiptail --msgbox "Account for user $USER has been disabled.\nAccount status: $STATUS" 8 60 --title "Disable User Account"
	break
################################################################
else
# Use whiptail to display an error message if the user did not enter a username
	whiptail --msgbox "Please enter a username." 8 40 --title "Disable User Account"
fi
done
continue

